version: '3.4'

services:
  smakownia.gateway.api:
    image: ${DOCKER_REGISTRY-}smakowniagatewayapi
    build:
      context: .
      dockerfile: src/Smakownia.Gateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8000:80
    networks:
      - smakownia

networks:
  smakownia:
    name: smakownia
