version: '3.4'

services:
  smakownia.gateway.api:
    image: ${DOCKER_REGISTRY-}smakowniagatewayapi
    build:
      context: .
      dockerfile: src/Smakownia.Gateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 8080:80
    volumes:
      - smakownia-upload:/app/upload
    networks:
      - smakownia

volumes:
  smakownia-upload:
    name: smakownia-upload

networks:
  smakownia:
    name: smakownia
